version: '3'

services:

  # Go Service deps

  godemoserv:
    build:
      context: .
      dockerfile: GoDemoService/cmd/service/Dockerfile
    ports:
      - "8083:8083"
#      - "8080:8080"
    environment:
      - OUTBOUND_HOST_PORT=localhost:8080
      - OUTBOUND_GET_ENDP=balance
      - SERVICE_PORT=8083
      - SERVICE_NAME=godemoservice
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_SERVICE_NAME=godemoservice

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=memory
      - QUERY_BASE_PATH=/jaeger
      - COLLECTOR_PORT=14250
      - HTTP_PORT=14268
      - GRPC_PORT=14250
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    command:
      - "--memory.max-traces=5000"
      - "--query.base-path=/jaeger/ui"
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4319:4317"
      - "14250:14250"
      - "14268:14268"

  locust-godemoserv:
    image: locustio/locust
    command: -P 8099 -f /locust-tasks/locustfile.py --host http://godemoserv:8083
    ports:
      - "8099:8099"
    volumes:
      - ./GoDemoService/:/locust-tasks
    depends_on:
      - godemoserv

  swagger-ui-godemoservice:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container-godemoservice"
    ports:
      - "8084:8080"
    volumes:
      - ./GoDemoService/documentation/swagger.yaml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml

  # Python Service deps

  pybankserv:
    build:
      context: .
      dockerfile: PyBankService/service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=pybankserv
      - SERVICE_PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=pybankserv
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    depends_on:
      - otel-collector

  locust-pybankserv:
    image: locustio/locust
    command: -P 8089 -f /locust-tasks/locustfile.py --host http://pybankserv:8080
    ports:
      - "8089:8089"
    volumes:
      - ./PyBankService/:/locust-tasks
    depends_on:
      - pybankserv

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
    volumes:
      - ./PyBankService/config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: [ "--config=/etc/otel-collector-config.yaml" ]

  swagger-ui-pybankservice:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui-container-pybankservice"
    ports:
      - "8081:8080"
    volumes:
      - ./PyBankService/documentation/swagger.yaml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml

  grafana:
    image: grafana/grafana:10.4.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/