version: '3'

services:
  pybankserv:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=pybankservice
      - SERVICE_PORT=8080
    networks:
      vpcbr:
        # ipv4_address: 10.5.0.6

  locust:
    image: locustio/locust
    command: -P 8089 -f /locust-tasks/locustfile.py --host http://pybankserv:8080    # change didn't work
    ports:
      - "8089:8089"
    volumes:
      - ./:/locust-tasks
    networks:
      vpcbr:
        # ipv4_address: 10.5.0.5
    depends_on:
      - pybankserv

# https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose
# https://stackoverflow.com/questions/48379107/how-can-i-ping-other-containers-in-a-docker-network-through-their-hostname
networks:
  vpcbr:
    driver: bridge
    # ipam:
    #  config:
    #    - subnet: 10.5.0.0/16
    #      gateway: 10.5.0.1
