version: '3'

services:
  pybankserv:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=pybankserv
      - SERVICE_PORT=8080


  locust:
    image: locustio/locust
    command: -P 8089 -f /locust-tasks/locustfile.py --host http://pybankserv:8080    # change didn't work
    ports:
      - "8089:8089"
    volumes:
      - ./:/locust-tasks
    depends_on:
      - pybankserv
