version: '3'

services:
  pybankserv:
    build:
      context: .
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=pybankserv
      - SERVICE_PORT=8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=pybankserv
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    depends_on:
      - otel-collector

  locust:
    image: locustio/locust
    command: -P 8089 -f /locust-tasks/locustfile.py --host http://pybankserv:8080
    ports:
      - "8089:8089"
    volumes:
      - ./:/locust-tasks
    depends_on:
      - pybankserv

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
