version: '3'
services:
  godemoserv:
    build:
      context: .
      dockerfile: cmd/service/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - OUTBOUND_HOST_PORT=localhost:8080
      - SERVICE_PORT=8083
      - SERVICE_NAME=godemoservice
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
